excluded:
  - Pods
  - SwatchBox/DataBase/Models/RAW
  - SwatchBox/Resources/R.generated.swift
disabled_rules:
  - todo
  - trailing_whitespace
  - identifier_name

opt_in_rules:
  - explicit_type_interface
  - force_unwrapping
  - force_cast


force_cast: warning
force_unwrapping: warning

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 15
  error: 20
vertical_whitespace:
  max_empty_lines: 2
large_tuple:
  warning: 3
  error: 4
line_length:
  warning: 250
  error: 500
function_body_length:
  warning: 75
  error: 100
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 600
  error: 700
function_parameter_count:
  warning: 10
  error: 11
